name: Build, Push and Deploy a Docker Image to Railway

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Log in to the Container registry
#        uses: docker/login-action@v3.3.0
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Download Encore CLI script
#        uses: sozo-design/curl@v1.0.2
#        with:
#          args: --output install.sh -L https://encore.dev/install.sh
#
#      - name: Install Encore CLI
#        run: bash install.sh
#
#      - name: Build Docker image
#        run: /home/runner/.encore/bin/encore build docker myapp
#
#      - name: Tag Docker image
#        run: docker tag myapp ghcr.io/${{ github.repository }}:latest
#
#      - name: Push Docker image
#        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: >- 
            --request POST
            --url https://backboard.railway.com/graphql/v2
            --header 'Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}'
            --header 'Content-Type: application/json'

#      - name: Trigger Railway deployment
#        uses: octokit/graphql-action@v2.x
#        with:
#          query: |
#            mutation ServiceInstanceRedeploy {
#               serviceInstanceRedeploy(
#                   environmentId: "acd168f1-37c4-4a1e-86e4-206d07568f2c"
#                   serviceId: "945e37da-1034-446e-9610-2af87582d634"
#               )
#            }
#        headers:
#          Authorization: ${{ secrets.RAILWAY_API_TOKEN }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# build-push-deploy-image2:
#   runs-on: ubuntu-latest
#   container: encoredotdev/encore:latest
#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4
#
#     - name: Log in to the Container registry
#       uses: docker/login-action@v3.3.0
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#
#     - name: Build Docker image
#       run: encore build docker myapp
#
#     - name: Tag Docker image
#       run: docker tag myapp ghcr.io/${{ github.repository }}:latest
#
#     - name: Push Docker image
#       run: docker push ghcr.io/${{ github.repository }}:latest
