name: Build, Push and Deploy a Docker Image

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Encore CLI
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - name: Log in to the Container registry
        run: docker login registry.digitalocean.com -u simon@encore.dev -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker image
        run: /home/runner/.encore/bin/encore build docker myapp

      - name: Tag Docker image
        run: docker tag myapp registry.digitalocean.com/ekerfelt/test:latest

      - name: Push Docker image
        run: docker push registry.digitalocean.com/ekerfelt/test:latest
